---
- hosts: tag_Name_demo
  remote_user: ec2-user
  become: True
  #  pre_tasks:
  #  - name: load vars
  #   include_vars: "{{ item }}"
  #   with_items:
  #     - "apache/defaults/main.yml"
  #   no_log: True
  #   tags: always
  roles:
    - { role: mysql }
            
